-- Tshwane Plan Examiner Bot - Database Schema
-- Run in Supabase SQL Editor

-- Enable storage
INSERT INTO storage.buckets (id, name, public) VALUES ('plans', 'plans', true);

-- Examinations table
CREATE TABLE IF NOT EXISTS examinations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT NOT NULL,
  erf_number TEXT,
  coverage_pct INTEGER,
  zoning TEXT,
  setback_front_m INTEGER,
  setback_side_m INTEGER,
  storeys INTEGER,
  status TEXT NOT NULL,
  plan_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index
CREATE INDEX IF NOT EXISTS idx_examinations_phone ON examinations(phone);
CREATE INDEX IF NOT EXISTS idx_examinations_created ON examinations(created_at DESC);

-- RLLS
ALTER TABLE examinations ENABLE ROW LEVEL SECURITY;

-- Allow public inserts (bot writes)
CREATE POLICY "Allow bot inserts" ON examinations FOR INSERT WITH CHECK (true);

-- Allow public reads for stats
CREATE POLICY "Allow public reads" ON examinations FOR SELECT USING (true);

-- Optional: Create view for dashboard
CREATE VIEW recent_examinations AS
SELECT
  phone,
  coverage_pct,
  zoning,
  status,
  created_at
FROM examinations
ORDER BY created_at DESC
LIMIT 100;