#!/bin/bash
# Sans Plan Examiner v2 - Quick Status
# Usage: bash .loki/scripts/status.sh

echo "╔══════════════════════════════════════════╗"
echo "║   Sans Plan Examiner v2 - Status         ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "📊 Project Stats:"
echo "   Commits: $(git rev-list --count HEAD 2>/dev/null || echo '?')"
echo "   Files tracked: $(git ls-files 2>/dev/null | wc -l)"
echo "   Last commit: $(git log -1 --oneline 2>/dev/null | cut -d' ' -f2-)"
echo ""
echo "🔄 Last 5 Commits:"
git log --oneline -5 2>/dev/null | sed 's/^/   /'
echo ""
echo "📁 Key Files:"
echo "   Client apply: client/apply.html"
echo "   Client track: client/track.html"
echo "   Admin: admin/admin.html"
echo "   API routes: src/routes/applications.js"
echo ""
echo "🌍 Endpoints:"
echo "   API: http://localhost:3000"
echo "   Admin: http://localhost:3000/admin/admin.html"
echo "   Apply: http://localhost:3000/client/apply.html"
echo "   Track: http://localhost:3000/client/track.html"
echo ""
echo "📋 v2 Features:"
echo "   ✓ 5-stage workflow"
echo "   ✓ 11 department routing"
echo "   ✓ AI severity classification"
echo "   ✓ Email notifications"
echo "   ✓ Admin department tabs"